services:
  cloudflare-dyndns:
    container_name: cloudflare-dyndns
    build: .
    # Removed port mapping - now accessed through Caddy
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - caddy-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP (will redirect to HTTPS)
      - "443:443"   # HTTPS
      - "443:443/udp" # HTTP/3
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    networks:
      - caddy-network
    depends_on:
      - cloudflare-dyndns

networks:
  caddy-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:
